language: node_js
node_js: 8

script:
  - npm install
  - npm run build
  - pip install --user awscli
  - aws s3 cp index.html s3://hhj-dayback/
  - aws s3 cp dist/* s3://hhj-dayback/dist/ --recursive

cache:
  bundler: true
  directories:
  - node_modules